version: '3'

services:
  agent:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: agent
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: "50m"
    restart: always